import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'danfergo' at '30-11-2016 16:37' with Gradle 3.0
 *
 * @author danfergo, @date 30-11-2016 16:37
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
